name: Run Tests

on:
  push:
    branches: [ "*" ]   # ✅ Run tests on ALL branches
  pull_request:
    branches: [ "*" ]   # ✅ Run tests on ALL PRs

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repo
      - uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # 4. Run tests
      - name: Run pytest
        run: pytest -v
